# Numpy Library

In [3]:
#fast
#convenient
#Efficient Storage

In [1]:
import numpy as np
np.__version__

'1.21.5'

# CREATE A 1-D ARRAY USING ARRAY()

In [2]:
import numpy as np
a=np.array([1,2,3])
print(a)
print(a.dtype)
print(a.shape)

[1 2 3]
int32
(3,)


# CREATE A 1-D ARRAY USING ARANGE()

In [8]:
import numpy as np
a=np.arange(1,4)
print(a)
print(a.dtype)
print(a.shape)

[1 2 3]
int32
(3,)


# CREATE A 2-D ARRAY USING ARRAY()

In [2]:
import numpy as np
b=np.array([[1,2,3,4],[5,6,7,8]])
print(b)
print(b.dtype)
print(b.shape)

[[1 2 3 4]
 [5 6 7 8]]
int32
(2, 4)


# CREATE A 2-D ARRAY USING ARANGE()

In [7]:
import numpy as np
a=np.arange(10).reshape(5,2) #MULTIPLY MUST RESULT SAME RANGE
print(a)
print(a.dtype)
print(a.shape)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
int32
(5, 2)


# CREATE A 3-D ARRAY USING ARRAY()

In [11]:
import numpy as np
a=np.array(
    [
    [[1,2],[3,4]],
    [[5,6], [7,8]],
    [[9,10],[11,12]]    
     ]
)
print(a)
print(a.dtype)
print(a.shape)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
int32
(3, 2, 2)


# CREATE A 3-D ARRAY USING ARANGE()

In [21]:
import numpy as np
a=np.arange(1,19).reshape(3,3,2)  #MULTIPLY MUST RESULT SAME RANGE
print(a)
print()
print(a.dtype)
print(a.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]

int32
(3, 3, 2)


# CREATING ARRAY OF ONES (1-D)

In [35]:
import numpy as np
a=np.ones(10,dtype=np.int32)
print(a)
print(a.dtype)
print(a.shape)

[1 1 1 1 1 1 1 1 1 1]
int32
(10,)


# CREATING ARRAY OF ONES(2-D)

In [38]:
import numpy as np
b=np.ones((3,3),dtype=np.int32)
print(b)
print(a.dtype)
print(a.shape)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
int32
(10,)


# CREATING ARRAY OF ONES(3-D)

In [40]:
import numpy as np
a=np.ones((3,3,3),dtype=np.int32)
print(a)
print(a.dtype)
print(a.shape)

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]
int32
(3, 3, 3)


# CREATING ARRAY OF ZEROS(1-D)

In [43]:
import numpy as np
a= np.zeros(3,dtype=np.int32)
print(a)
print(a.dtype)
print(a.shape)

[0 0 0]
int32
(3,)


# CREATING ARRAY OF ZEROS(2-D)

In [44]:
import numpy as np
a=np.zeros((3,3),dtype="int32")
print(a)
print(a.dtype)
print(a.shape)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
int32
(3, 3)


# CREATING ARRAY OF ZEROS(3-D)

In [47]:
import numpy as np
a=np.zeros((3,3,3),dtype="int32")
print(a)
print(a.dtype)
print(a.shape)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
int32
(3, 3, 3)


# CREATE AN ARRAY WITH RANDOM NUMBERS(1-D)

In [61]:
import numpy as np
a=np.random.randint(5,11,size=(3)) #1-10 size=reshape
print(a)
print(a.dtype)
print(a.shape)

[6 7 5]
int32
(3,)


# CREATE AN ARRAY WITH RANDOM NUMBERS(2-D)

In [64]:
import numpy as np
a=np.random.randint(1,11,size=(3,3))
print(a)
print(a.dtype)
print(a.shape)

[[6 3 8]
 [5 7 4]
 [5 4 6]]
int32
(3, 3)


# CREATE AN ARRAY WITH RANDOM NUMBERS(3-D)

In [66]:
import numpy as np
a=np.random.randint(1,11,size=(3,2,3))
print(a)
print(a.dtype)
print(a.shape)

[[[4 2 1]
  [7 6 3]]

 [[5 2 6]
  [9 1 3]]

 [[4 4 4]
  [7 1 2]]]
int32
(3, 2, 3)


# CREATE ARRAY WITH SINGLE LOW MULTIPLE HIGH

In [2]:
import numpy as np
a=np.random.randint(5,[10,20,30])
print(a)
print(a.dtype)
print(a.shape)

[ 9 12 29]
int32
(3,)


# CREATE ARRAY WITH MULTIPLE LOW SINGLE HIGH

In [4]:
import numpy as np
a=np.random.randint([10,20,30],50)
print(a)
print(a.dtype)
print(a.shape)

[38 26 42]
int32
(3,)


# CREATE ARRAY WITH MULTIPLE LOW MULTIPLE HIGH

In [6]:
import numpy as np
a=np.random.randint([1,2,3],[3,5,6],size=(3,2,3))      
print(a)
print(a.dtype)
print(a.shape)

[[[1 2 3]
  [1 3 4]]

 [[2 2 3]
  [1 2 5]]

 [[2 3 3]
  [2 4 4]]]
int32
(3, 2, 3)


# CREATE AN ARRAY USING RANDN()

In [8]:
import numpy as np
a = np.random.randn(3) #n=ANY FLOATING VALUE
print(a)
print(a.dtype)

[-0.38199105  0.37390346  1.82668423]
float64


In [10]:
import numpy as np
a = np.random.randn(3,3)
print(a)

[[-0.95967903  0.08671854  1.32650254]
 [ 0.76479507  0.19436158 -0.76355238]
 [-0.49228759 -1.17540494  0.11335255]]


# CREATE AN ARRAY USING RAND()

In [11]:
import numpy as np
a = np.random.rand(3,3)
print(a)
print(a.dtype)

[[0.55639285 0.64179274 0.26727228]
 [0.94159187 0.07920052 0.85577504]
 [0.5279845  0.07890741 0.75864092]]
float64


In [12]:
import numpy as np
a = np.random.rand(3,2,2)
print(a)
print(a.dtype)

[[[0.22332138 0.96190984]
  [0.81831501 0.90299166]]

 [[0.61434007 0.92456512]
  [0.15919419 0.20200413]]

 [[0.00265786 0.6473209 ]
  [0.03148421 0.55272133]]]
float64


# POSITIVE INDEXING IN ARRAY

In [13]:
#ARRAY IN 1-D
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr[3])

4


In [16]:
#ARRAY IN 2-D
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr[1,2])
print(arr[0,1])

6
2


In [20]:
#ARRAY IN 3-D
import numpy as np
arr=np.array([[[1,2,3],[1,2,3]],[[1,1,1],[2,2,2]],[[3,8,3],[4,9,4]]])
print(arr[2,0,1])
print(arr[2,1,1])

8
9


# NEGATIVE INDEXING IN ARRAY

In [7]:
#ARRAY IN 2-D
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[11,12,13],[14,15,16]])
print(arr[-1,-3])
print(arr[-4,-2])
print(arr[-2,-2])

14
2
12


In [10]:
#ARRAY IN 3-D
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])
#print(arr)
print(arr[-3,-2,-2])

2


# MIX (+,-,+)

In [17]:
#ARRAY IN 3-D
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[1,8,1],[2,5,2]],[[3,3,3],[4,4,4]]])
print(arr[-2,-1,-2])
print(arr[0,-1,2])
print(arr[1,-2,1])
print(arr[1,-1,1])
print(arr[-3,-2,1])

5
6
8
5
2


# NUMPY ARRAY SLICING

Slice elements from index 1 to index 5 from the following array :

In [20]:
import numpy as np
a = np.array([1,2,3,4,5,6,7])
print(a[1:5])

[2 3 4 5]


Slice elements from index 4 to the end of the array

In [21]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[4:])

[5 6 7]


Slice elements from the beginning to index 4(not included)

In [23]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[:4])

[1 2 3 4]


# NEGATIVE SLICING

 Slice  from the index 3 from the end to index 1 from the end

In [24]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])

[5 6]


Return every other element from index 1 to index 5

In [33]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[-1:-5:-2])

[7 5]


Return every other element from the entire array

In [34]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[::-2])

[7 5 3 1]


# SLICING 2-D ARRAY

From the second element,slice elements from index 1 to index 4 (not included):

In [29]:
import numpy as np
arr=np.array([[1,2,3,4,5],[4,5,6,7,8]])
print(arr[1,1:4])

[5 6 7]


From both arrays ,return index 2:

In [37]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,2])

[3 8]


From both elements ,slice index 1 to index 4 (not included),this wll return a 2-D array:

In [40]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:,1:4])

[[2 3 4]
 [7 8 9]]


# NUMPY ARRAY COPY VS VIEW

Here, in copy any changes made in copy will not affect original array or  changes made in original will not affect copy array

In view it does not own the data,any changes is done on any array then it will affect both the arrays

In [5]:
import numpy as np
arr = np.array([1,2,3,4,5])
print("Original Array: ",arr)

arr[0]=10
print(arr)
print()

x=arr.copy()
print("Copy Array: ",x)

x[0]=11
print(x)

Original Array:  [1 2 3 4 5]
[10  2  3  4  5]

Copy Array:  [10  2  3  4  5]
[11  2  3  4  5]


In [11]:
import numpy as np
arr = np.array([1,2,3,4,5])
print("Original Array: ",arr)

y=arr.view()
print("Viewed Array: ",y)

arr[0]=10
print(arr)
print(y)

Original Array:  [1 2 3 4 5]
Viewed Array:  [1 2 3 4 5]
[10  2  3  4  5]
[10  2  3  4  5]


# RESHAPE FUNCTION

RESHAPE MEANS CHANGING THE SHAPE OF AN ARRAY OR CHANGING THE NUMBER OF ROWS AND COLUMNS

In [20]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Original Array: ",arr) #1-D Array    
print()

#2-D Array
b= arr.reshape(5,2)
print("2-D Array with shape 5x2")
print(b)

c= arr.reshape(2,5)
print("2-D Array with shape 2x5")
print(c)

#3-D Array
d=arr.reshape(1,2,5)
print("3-D Arrat with shape 1x2x5")
print(d)

d=arr.reshape(2,1,5)
print("3-D Arrat with shape 2x1x5")
print(d)

Original Array:  [ 1  2  3  4  5  6  7  8  9 10]
2-D Array with shape 5x2
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
2-D Array with shape 2x5
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
3-D Arrat with shape 1x2x5
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]]
3-D Arrat with shape 2x1x5
[[[ 1  2  3  4  5]]

 [[ 6  7  8  9 10]]]


# ARRAY AGGREGATION FUNCTION

# SUM()

In [35]:
import numpy as np
arr = np.array([
    [[1,2,3,4,5],[6,7,8,9,10]],
    [[1,1,1,1,1],[1,1,1,1,1]]
         ])
print(arr)
#a = arr.sum()
print("\n",np.sum(arr))

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[ 1  1  1  1  1]
  [ 1  1  1  1  1]]]

 65


In [46]:
#np.sum(array_name , axis =0 or 1)
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)

print("\n Accross Rows:")  #Means adding in columns
print(np.sum(arr, axis=0))

print("\nAcross Columns:")#Means adding in rows
print(np.sum(arr, axis=1))    

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

 Accross Rows:
[ 7  9 11 13 15]

Across Columns:
[15 40]


# MEAN()

In [41]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print(np.mean(arr)) #Here , it means addition of arrays/No. of Elements

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
5.5


In [44]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print("\n Accross Rows")
print(np.mean(arr , axis=0))
print("\n Accross Columns")
print(np.mean(arr , axis =1))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

 Accross Rows
[3.5 4.5 5.5 6.5 7.5]

 Accross Columns
[3. 8.]


# STANDARD DEVIATION

In [51]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print(np.std(arr))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2.8722813232690143


In [54]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print("\n Accross Rows")
print(np.std(arr , axis=0))

print("\n Accross Columns")
print(np.std(arr  , axis = 1))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

 Accross Rows
[2.5 2.5 2.5 2.5 2.5]

 Accross Columns
[1.41421356 1.41421356]


# VARIANCE()

In [55]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print(np.var(arr))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
8.25


In [61]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print("\n Accross Rows:")  #Means adding in columns
print(np.var(arr,axis=0))
print("\nAcross Columns:")#Means adding in rows
print(np.var(arr,axis=1))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

 Accross Rows:
[6.25 6.25 6.25 6.25 6.25]

Across Columns:
[2. 2.]


# Minimum()

In [63]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print(np.min(arr))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
1


In [64]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print("\n Accross Rows:")  #Means adding in columns
print(np.min(arr,axis=0))
print("\nAcross Columns:")#Means adding in rows
print(np.min(arr,axis=1))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

 Accross Rows:
[1 2 3 4 5]

Across Columns:
[1 6]


# MAXIMUM()

In [65]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print(np.max(arr))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
10


In [66]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print("\n Accross Rows:")  #Means adding in columns
print(np.max(arr,axis=0))
print("\nAcross Columns:")#Means adding in rows
print(np.max(arr,axis=1))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

 Accross Rows:
[ 6  7  8  9 10]

Across Columns:
[ 5 10]
